config/routes.rb
StaffAgency::Application.routes.draw do
  get "home/index"

  resources :skills do 
    
  end

  resources :employees do 
    resources :vacancies, :skills   
  end  
  
  resources :vacancies do
    resources :employees, :skills
  end  

  root :to => "home#index"

end

app/models/employee.rb
# encoding: utf-8
class Employee < ActiveRecord::Base
  self.per_page = 10
  #set_primary_key :employee_id
    
  has_many :skills
  has_many :vacancies, :through => :skills
  
  validates :name, :contact_info, :status, :salary, :presence => true
  
  validates_format_of :name, 
  :with => /[а-яА-ЯёЁ $]/,
  :message => "can only contain cyrillic letters and spaces."
  
  validates_length_of :name, 
  :tokenizer => lambda {|str| str.scan(/[а-яА-ЯёЁ]/)},
  :minimum => 3,  
  :message => "Must have only %{count} cyrillic words"
  
  validates_uniqueness_of :contact_info, :allow_blank => false
  
  validates_format_of :contact_info, 
  :with => /^([a-zA-Z][\w\.-]*[a-zA-Z0-9]@[a-zA-Z0-9][\w\.-]*[a-zA-Z0-9]\.[a-zA-Z][a-zA-Z\.]*[a-zA-Z]|[1]?[\-|\s|\.]?\(?[0-9]{3}\)?[\-|\s|\.]?[0-9]{3}[\-|\s|\.]?[0-9]{2}[\-|\s|\.]?[0-9]{2})$/,
  :message => "is not a valid phone number (incl. operator code) or email address"
  
  #validates :salary, :numeric? => true
  
  def numeric?(object)
    true if Float(object) rescue false
  end
  
  def findByVacancy(name)
     Employee.find(:all, :conditions => ["name = #{name}", true])
  end
  
  def getAllSkills()
    Skill.find(:all, :conditions => ['name = ?', true])
  end

  def findAllValidVacancies()
    Vacancies.find_all_by_skills(self.skills)   
  end  
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      #format.js { render employee}
      format.html # index.html.erb
      format.json { render json: @employees }
    end
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
    @employee = Employee.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/new
  # GET /employees/new.json
  def new
    @employee = Employee.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @employee }
    end
  end

  # GET /employees/1/edit
  def edit
    @employee = Employee.find(params[:id])
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(params[:employee])

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render json: @employee, status: :created, location: @employee }
      else
        format.html { render action: "new" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /employees/1
  # PUT /employees/1.json
  def update
    @employee = Employee.find(params[:id])

    respond_to do |format|
      if @employee.update_attributes(params[:employee])
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    @employee.destroy

    respond_to do |format|
      format.html { redirect_to employees_url }
      format.json { head :no_content }
    end
  end
  
  def find_employee
    @employee = Employee.find params[:id]
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_for(@employee)  do |f| %>
  <% if @employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% @employee.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :contact_info %><br />
    <%= f.text_field :contact_info %>
  </div>
  <div class="field">
    <%= f.label :status %><br />
    <%= f.check_box :status %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
   <div class="field" id="select_skills">
   <%= f.label :skill %><br /> 
   <%= f.select :skill_ids, Skill.all.collect {|x| [x.name, x.id]}, {}, :multiple => true %>
  </div> 
  <div >
  <%= link_to "Create a new skill", new_skill_path, :remote => true, :method => :post, :onclick=>"window.open(this.href,'create_skill', 'height=300, width=300');return false;" 
   %></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing employee</h1>

<%= render 'form' %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<h1>Listing employees</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Contact info</th>
    <th>Status</th>
    <th>Salary</th>
    <th>Skills</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @employees.each do |employee| %>
  <tr>   
    <td><%= employee.name %></td>
    <td><%= employee.contact_info %></td>
    <td><%= employee.status %></td>
    <td><%= employee.salary %></td>
    <td><%= employee.skills.collect {|x| [x.name]} %></td>
    <td><%= link_to 'Show', employee %></td>
    <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
    <td><%= link_to 'Destroy', employee, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<br />

<%= link_to 'New Employee', new_employee_path %>
<%= will_paginate @employees %>

app/views/employees/new.html.erb
<h1>New employee</h1>

<%= render 'form' %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @employee.name %>
</p>

<p>
  <b>Contact info:</b>
  <%= @employee.contact_info %>
</p>

<p>
  <b>Status:</b>
  <%= @employee.status %>
</p>

<p>
  <b>Salary:</b>
  <%= @employee.salary %>
</p>

<p>
  <b>Skills:</b>  
  <%= @employee.skills.collect {|x| [x.name]} %>
</p>


<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %> |
<%= link_to 'Find Vacancies',
 :controller => "vacancies",
 :action => "index",
 :direction => "desc",
 :sort => "Salary", 
 :employee => @employee.id,
 :skills => @employee.skills %>