config/routes.rb
StaffAgency::Application.routes.draw do
  get "home/index"

  resources :skills do 
    
  end

  resources :employees do 
    resources :vacancies, :skills   
  end  
  
  resources :vacancies do
    resources :employees, :skills
  end  

  root :to => "home#index"

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  #has_many :employees, :through => :skills
  self.per_page = 10
  #set_primary_key :vacancy_id
  has_many :skills
  has_many :employees, :through => :skills
  
  validates :position,:salary,:contact_info,:expiration, :salary, :presence => true
  validates :contact_info, :email_or_phone => true
  
  def self.search(search)
  if search
    where('position LIKE ?', "%#{search}%")
  else
    scoped
  end
  end
  
  def find_vacancies_by_range(dt)
     Vacancy.find(:creationDate => Date.current - dt.. Date.current)
  end
  
  def find_vacancies_by_position(pos)
     Vacancy.find(:position => pos)
  end
     
end

app/controllers/vacancies_controller.rb
class VacanciesController < ApplicationController
  # GET /vacancies
  # GET /vacancies.json
  helper_method :sort_column, :sort_direction
  
  def index

    #@vacancies = Vacancy.all
    @vacancies = Vacancy.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 5)

   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vacancies }
    end   
  end

  def find

    #@vacancies = Vacancy.all
    @vacancies = Vacancy.search(params[:search]).order(sort_column + " " + sort_direction).paginate(:page => params[:page], :per_page => 5)

   
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @vacancies }
    end   
  end

  # GET /vacancies/1
  # GET /vacancies/1.json
  def show
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @vacancy }
    end
  end

  # GET /vacancies/new
  # GET /vacancies/new.json
  def new
    @vacancy = Vacancy.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @vacancy }
    end
  end

  # GET /vacancies/1/edit
  def edit
    @vacancy = Vacancy.find(params[:id])
  end

  # POST /vacancies
  # POST /vacancies.json
  def create
    @vacancy = Vacancy.new(params[:vacancy])

    respond_to do |format|
      if @vacancy.save
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully created.' }
        format.json { render json: @vacancy, status: :created, location: @vacancy }
      else
        format.html { render action: "new" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /vacancies/1
  # PUT /vacancies/1.json
  def update
    @vacancy = Vacancy.find(params[:id])

    respond_to do |format|
      if @vacancy.update_attributes(params[:vacancy])
        format.html { redirect_to @vacancy, notice: 'Vacancy was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @vacancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vacancies/1
  # DELETE /vacancies/1.json
  def destroy
    @vacancy = Vacancy.find(params[:id])
    @vacancy.destroy

    respond_to do |format|
      format.html { redirect_to vacancies_url }
      format.json { head :no_content }
    end
  end
  
  def sort_column
    Vacancy.column_names.include?(params[:sort]) ? params[:sort] : "position"
  end
  
  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
  
   def find_vacancy
    @vacancy = Vacancy.find params[:id]
   end
end

app/helpers/vacancies_helper.rb
module VacanciesHelper
end

app/views/vacancies/_form.html.erb
<%= form_for(@vacancy) do |f| %>
  <% if @vacancy.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vacancy.errors.count, "error") %> prohibited this vacancy from being saved:</h2>

      <ul>
      <% @vacancy.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :position %><br />
    <%= f.text_field :position %>
  </div>
  <div class="field">
    <%= f.label :creationDate %><br />
    <%= f.date_select :creationDate %>
  </div>
  <div class="field">
    <%= f.label :expiration %><br />
    <%= f.text_field :expiration %>
  </div>
  <div class="field">
    <%= f.label :salary %><br />
    <%= f.text_field :salary %>
  </div>
  <div class="field">
    <%= f.label :contact_info %><br />
    <%= f.text_field :contact_info %>
  </div>
   <div class="field">
   <%= f.label :skill %><br /> 
   <%= f.select :skill_ids, Skill.all.collect {|x| [x.name, x.id]}, {}, :multiple => true, :remote => true %>
  </div>  
  <div class="actions"> 
  <%= link_to "Create a new skill", new_skill_path, :remote => true, :method => :post, :onclick=>"window.open(this.href,'create_skill', 'height=300, width=300');return false;" 
   %></div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vacancies/_vacancies.html.erb
<%= hidden_field_tag :direction, params[:direction] %>
<%= hidden_field_tag :sort, params[:sort] %>
<table class="pretty">
  <tr>
    <th>Position</th>
    <th>Creationdate</th>
    <th>Expiration</th>
    <th><%= sortable "Salary" %></th>
    <th>Contact info</th>
    <th>Skills</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @vacancies.each do |vacancy| %>
  <tr>
    <td><%= vacancy.position %></td>
    <td><%= vacancy.creationDate %></td>
    <td><%= vacancy.expiration %></td>
    <td><%= vacancy.salary %></td>
    <td><%= vacancy.contact_info %></td>
     <td><%= vacancy.skills.collect {|x| [x.name]} %></td>
    <td><%= link_to 'Show', vacancy %></td>
    <td><%= link_to 'Edit', edit_vacancy_path(vacancy) %></td>
    <td><%= link_to 'Destroy', vacancy, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<%= will_paginate @vacancies %>

app/views/vacancies/edit.html.erb
<h1>Editing vacancy</h1>

<%= render 'form' %>

<%= link_to 'Show', @vacancy %> |
<%= link_to 'Back', vacancies_path %>

app/views/vacancies/index.html.erb
<h1>Listing vacancies</h1>	

<%= form_tag vacancies_path, :method => 'get', :id => "vacancies_search" do %>
<p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :position => nil %>
  </p>
  <div id="vacancies"><%= render 'vacancies' %></div>
<% end %>

<br />

<%= link_to 'New Vacancy', new_vacancy_path %>

app/views/vacancies/new.html.erb
<h1>New vacancy</h1>

<%= render 'form' %>

<%= link_to 'Back', vacancies_path %>

app/views/vacancies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Position:</b>
  <%= @vacancy.position %>
</p>

<p>
  <b>Creationdate:</b>
  <%= @vacancy.creationDate %>
</p>

<p>
  <b>Expiration:</b>
  <%= @vacancy.expiration %>
</p>

<p>
  <b>Salary:</b>
  <%= @vacancy.salary %>
</p>

<p>
  <b>Contact info:</b>
  <%= @vacancy.contact_info %>
</p>

<p>
  <b>Skills:</b>
  <%= @vacancy.skills.collect {|x| [x.name]} %>
</p>


<%= link_to 'Edit', edit_vacancy_path(@vacancy) %> |
<%= link_to 'Back', vacancies_path %> |
<%= link_to 'Find All Employees', vacancy_employees_path(@vacancy)%>