config/routes.rb
StaffAgency::Application.routes.draw do
  get "home/index"

  resources :skills do 
    
  end

  resources :employees do 
    resources :vacancies, :skills   
  end  
  
  resources :vacancies do
    resources :employees, :skills
  end  

  root :to => "home#index"

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  self.per_page = 10
  attr_accessible :name
  belongs_to :employee
  belongs_to :vacancy

  has_many :employees
  has_many :vacancies
  #belongs_to :employee, :class_name => 'Employee'
  #belongs_to :vacancy, :class_name => 'Vacancy'

  #set_primary_key :skill_id
  #set_primary_key :vacancy_id
  
  validates :name, :uniqueness => true
  validates :name, :presence => true
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  # GET /skills
  # GET /skills.json
  def index
    @skills = Skill.all.paginate(:page => params[:page], :per_page => 10)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @skills }
      format.js 
    end
  end

  def show_list
     @skills = Skill.all
     respond_to do |format|
        format.html # show_list.html.erb        
        format.json { render json: @skills }
     end
  end   

  # GET /skills/1
  # GET /skills/1.json
  def show
    @skill = Skill.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/new
  # GET /skills/new.json
  def new
    @skill = Skill.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @skill }
    end
  end

  # GET /skills/1/edit
  def edit
    @skill = Skill.find(params[:id])
  end

  # POST /skills
  # POST /skills.json
  def create
    @skill = Skill.new(params[:skill])

    respond_to do |format|
      if @skill.save
        format.html { redirect_to @skill, notice: 'Skill was successfully created.' }
        format.json { render json: @skill, status: :created, location: @skill }
        format.js
      else
        format.html { render action: "new" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
        format.js {render 'error'}
      end
    end
  end

  # PUT /skills/1
  # PUT /skills/1.json
  def update
    @skill = Skill.find(params[:id])

    respond_to do |format|
      if @skill.update_attributes(params[:skill])
        format.html { redirect_to @skill, notice: 'Skill was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @skill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /skills/1
  # DELETE /skills/1.json
  def destroy
    @skill = Skill.find(params[:id])
    @skill.destroy

    respond_to do |format|
      format.html { redirect_to skills_url }
      format.json { head :no_content }
    end
  end
 
  
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/views/skills/_form.html.erb
<%= form_for(@skill, :remote => true) do |f| %>
  <% if @skill.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@skill.errors.count, "error") %> prohibited this skill from being saved:</h2>

      <ul>
      <% @skill.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/skills/edit.html.erb
<h1>Editing skill</h1>

<%= render 'form' %>

<%= link_to 'Show', @skill %> |
<%= link_to 'Back', skills_path %>

app/views/skills/index.html.erb
<h1>Listing skills</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @skills.each do |skill| %>
  <tr>
    <td><%= skill.name %></td>
    <td><%= link_to 'Show', skill %></td>
    <td><%= link_to 'Edit', edit_skill_path(skill) %></td>
    <td><%= link_to 'Destroy', skill, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>
<%= will_paginate @skills %>



<br />

<%= link_to 'New Skill', new_skill_path %>

app/views/skills/new.html.erb
<h1>New skill</h1>

<%= render 'form' %>

<%= link_to 'Back', skills_path %>

app/views/skills/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @skill.name %>
</p>

<%= link_to 'Edit', edit_skill_path(@skill) %> |
<%= link_to 'Back', skills_path %>